{"uuid": "2c097f96-364e-4080-b2ef-f22383d75456", "children": ["a7ea3641-3214-4d9f-b86c-905150b89bc4"], "befores": [{"name": "set_up", "status": "passed", "start": 1653509619105, "stop": 1653509698088}], "afters": [{"name": "set_up::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Check your password or email\nMessage: unexpected alert open: {Alert text : Check your password or email}\n  (Session info: chrome=101.0.4951.67)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0063B8F3+2406643]\n\tOrdinal0 [0x005CAF31+1945393]\n\tOrdinal0 [0x004BC748+837448]\n\tOrdinal0 [0x0050AE37+1158711]\n\tOrdinal0 [0x00504243+1131075]\n\tOrdinal0 [0x004DE636+976438]\n\tOrdinal0 [0x004DF546+980294]\n\tGetHandleVerifier [0x008A9612+2498066]\n\tGetHandleVerifier [0x0089C920+2445600]\n\tGetHandleVerifier [0x006D4F2A+579370]\n\tGetHandleVerifier [0x006D3D36+574774]\n\tOrdinal0 [0x005D1C0B+1973259]\n\tOrdinal0 [0x005D6688+1992328]\n\tOrdinal0 [0x005D6775+1992565]\n\tOrdinal0 [0x005DF8D1+2029777]\n\tBaseThreadInitThunk [0x7612FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77D47A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77D47A4E+238]\n\n", "trace": "  File \"c:\\users\\imoe001\\pycharmprojects\\pythonproject\\pythonproject3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\imoe001\\pycharmprojects\\pythonproject\\pythonproject3\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\IMOE001\\PycharmProjects\\pythonProject\\pythonProject3\\Web\\Base\\base.py\", line 20, in set_up\n    self.driver.close()\n  File \"c:\\users\\imoe001\\pycharmprojects\\pythonproject\\pythonproject3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 943, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\imoe001\\pycharmprojects\\pythonproject\\pythonproject3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\imoe001\\pycharmprojects\\pythonproject\\pythonproject3\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 246, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1653509703419, "stop": 1653509703434}], "start": 1653509619105, "stop": 1653509703435}